name: create-aws-env

# trrigered manualy from github UI
on:
  workflow_dispatch:
    inputs:
      tfAction:
        description: 'Select  the terraform action you want to run - apply/destroy'
        default: 'apply'
        enum: ['apply', 'destroy']

jobs:
  create-aws-env:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code from prod branch
        uses: actions/checkout@v2
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: Create env
        run: |
          pip install -r infra/requirements.txt
          python infra/main.py --workspace ${GITHUB_WORKSPACE}/infra --awsAccess ${{ secrets.AWS_ACCESS_KEY_ID }} \
            --awsSecret ${{ secrets.AWS_SECRET_ACCESS_KEY}} --tfAction ${{ github.event.inputs.tfAction }}

