name: update-webapp-content

on:
  push:
    branches:
      - main

jobs:
  upload-to-s3:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install AWS CLI
      run: sudo apt-get install awscli -y --fix-missing

    - name: Upload index.html to S3
      run: aws s3 cp app-content/index.html s3://${{ secrets.WEB_APP_BUCKET_NAME }}/index.html
